parse boolean txt records (keys without value) correctly
mjansson/mdns pull request #63
Opened 2022-07-15 16:11 UTC by ChristianHillenbrand

Hey :) While playing around with your mdns library i noticed that txt records containing no values weren't parsed correctly. The problem is that they are discarded if no separator ('=') has been found yet, though the entry is completely reasonable. I provided a small fix for this issue and it would be great if you merge it into the main branch :)
Have a great weekend!

2022-07-22 13:19 UTC, mjansson requested changes
Nice catch, a few modifications in my comments to keep the validation of ASCII-only data

2022-07-22 13:19 UTC, mjansson commented on mdns.h
> +		size_t separator = sublength;
Problem here is that a TXT record with non-ASCII data will be parsed in violation of the standard. Keep this assignment but add an assign to reset separator to 0 if non-ASCII is encountered, as well as restoring the zero check.

2022-07-22 13:19 UTC, mjansson commented on mdns.h
>  			if ((strdata[c] < 0x20) || (strdata[c] > 0x7E))
Add { separator = 0; break; } here

2022-07-22 13:19 UTC, mjansson commented on mdns.h
> -		if (!separator)
Restore this check

2022-08-09 18:52 UTC, ChristianHillenbrand commented
Allright I implemented the modifications as you suggested ;-)

2022-08-09 20:46 UTC, mjansson approved these changes
Looks good now, thanks!

2022-08-09 20:46 UTC, merged